### ISSUE TITLE
Opening in new tab?

### ISSUE THREAD

**Issue by mikeerickson** [solobat/atom-open-this#1]
First of all, thank you for creating this, very handy

Is there a way to open in a new tab as opposed to replacing the current file?

```
cmd-k f n ?
cmd-k f t ?
```

**Comment by solobat** [comment]
I think this is not a problem, if the current file is opened with double-click, the new file will be opened in a new tab.

**Comment by mikeerickson** [comment]
Ah yes, the file was just opened via "preview" I see what you mean :). Thx for response
